---
package_update_enabled: false
package_update_install_from_local_repo: true
package_update_repo_source: ./repo/update
package_update_repo_dest: /media/installation/update
package_update_cleanup_installation_dir: true
package_update_installation_dir: /media/installation
package_update_cache_valid_time: 3600
package_update_allow_downgrade: false
package_update_packages:
  - name: libssl3t64
  - name: openssl
  - name: inetutils-telnet
  - name: telnet
  - name: vim
  - name: vim-common
  - name: vim-runtime
  - name: vim-tiny
  - name: xxd
