---
dns_time_services_enabled: false
dns_time_services_load_images: true

dns_time_services_base_dir: /opt/ansible-dns-time
dns_time_services_image_dir: "{{ dns_time_services_base_dir }}/images"

dns_server_enabled: true
dns_server_image: local/bind9:offline
dns_server_image_tar: ./repo/docker-images/bind9.tar
dns_server_container_name: dns-server
dns_server_config_dir: "{{ dns_time_services_base_dir }}/bind"
dns_server_command: "named -g -c /etc/bind/named.conf"
dns_server_allow_query:
  - 172.16.0.0/16
dns_server_forwarders: []
dns_server_extra_options: []

time_server_enabled: true
time_server_image: local/chrony:offline
time_server_image_tar: ./repo/docker-images/chrony.tar
time_server_container_name: time-server
time_server_config_dir: "{{ dns_time_services_base_dir }}/chrony"
time_server_command: "chronyd -d -f /etc/chrony/chrony.conf"
time_server_extra_docker_args: "--cap-add SYS_TIME --cap-add SYS_NICE"
time_server_allow:
  - 172.16.0.0/16
time_server_upstream_servers: []
time_server_local_stratum: 10
