---
docker_swarm_enabled: false
docker_swarm_manager_group: swarm_managers
docker_swarm_worker_group: swarm_workers
docker_swarm_target_group: "swarm_managers:swarm_workers"
docker_swarm_listen_addr: "0.0.0.0:2377"
docker_swarm_port: 2377
docker_swarm_force_reset: false
docker_swarm_leave_force: true
docker_swarm_manager_addr: ""

docker_swarm_manage_iptables: false
docker_swarm_manage_encrypted_overlay_esp: false

docker_swarm_group_labels: {}
docker_swarm_node_labels: {}
