---
docker_swarm_enabled: false
docker_swarm_manager_group: swarm_managers
docker_swarm_worker_group: swarm_workers
docker_swarm_target_group: "swarm_managers:swarm_workers"
docker_swarm_listen_addr: "0.0.0.0:2377"
docker_swarm_port: 2377
docker_swarm_force_reset: false
docker_swarm_leave_force: true
docker_swarm_manager_addr: ""

docker_swarm_manage_iptables: false
docker_swarm_manage_encrypted_overlay_esp: false
docker_swarm_manage_ipsets: true
docker_swarm_ipset_prefix: swarm
docker_swarm_ipset_managers_name: swarm_managers
docker_swarm_ipset_nodes_name: swarm_nodes
docker_swarm_ipset_service_clients_name: app_clients
docker_swarm_ipset_logger_name: syslog_nodes
docker_swarm_external_service_ipset_names:
  database: mysql_nodes
  storage: minio_nodes
docker_swarm_service_allowed_source_ips: []
docker_swarm_service_host_interface: ""
docker_swarm_service_bridge_interface: docker_gwbridge
docker_swarm_service_ports:
  - 80
docker_swarm_service_ports_by_host: {}
docker_swarm_external_service_rules: []
docker_swarm_external_service_rules_by_host: {}
docker_swarm_logger_node_tag: logger
docker_swarm_logger_port: 514
docker_swarm_logger_protocols:
  - tcp
  - udp
docker_swarm_docker_user_drop_enabled: false

docker_swarm_group_labels: {}
docker_swarm_node_labels: {}
