---
iptables_enabled: false
iptables_target_group: iptables_targets
iptables_reset_enabled: true
iptables_reset_chains:
  - INPUT
  - OUTPUT
iptables_manage_ipsets: true
iptables_ipset_persist: true
iptables_ipset_save_path: /etc/iptables/ipsets
iptables_persist: true
iptables_save_path: /etc/iptables/rules.v4
iptables_ipset_prefix: common
iptables_ipset_ssh_sources_name: common_ssh_sources
iptables_ipset_ssh_targets_name: common_ssh_targets
iptables_ipset_service_sources_name: common_service_sources
iptables_ipset_dns_time_servers_name: common_dns_time_servers
iptables_ipset_dns_time_clients_name: common_dns_time_clients
iptables_ipset_zabbix_servers_name: common_zabbix_servers
iptables_ipset_zabbix_agents_name: common_zabbix_agents
iptables_ssh_whitelist_ips_raw: ""
iptables_ssh_port: 22
iptables_service_allowed_source_ips: []
iptables_external_service_rules: []
iptables_inbound_service_rules: []
iptables_ip_port_rules: []
iptables_zabbix_server_ips: []
iptables_zabbix_agent_port: 10050
iptables_zabbix_server_port: 10051
iptables_dns_time_server_ips: []
iptables_dns_time_client_sources: []
iptables_dns_port: 53
iptables_time_port: 123
iptables_block_enabled: false
iptables_block_chains:
  - INPUT
  - OUTPUT
iptables_accept_chains:
  - INPUT
  - OUTPUT
