---
iptables_enabled: false
iptables_target_group: iptables_targets
iptables_reset_enabled: true
iptables_reset_chains:
  - INPUT
  - OUTPUT
iptables_ssh_whitelist_ips_raw: ""
iptables_ssh_port: 22
iptables_service_allowed_source_ips: []
iptables_external_service_rules: []
iptables_ip_port_rules: []
iptables_zabbix_server_ips: []
iptables_zabbix_agent_port: 10050
iptables_zabbix_server_port: 10051
iptables_dns_time_server_ips: []
iptables_dns_time_client_sources: []
iptables_dns_port: 53
iptables_time_port: 123
iptables_block_enabled: false
iptables_block_chains:
  - INPUT
  - OUTPUT
